### ISSUE TITLE
pyrxvm/pyrxvm.c: needs review/audit by someone who knows python C API better than me

### ISSUE THREAD

**Issue by eriknyquist** [eriknyquist/librxvm#5]
I'm pretty sure I did everything correctly, but there may be a reference leak somewhere, or I could have otherwise messed something up.

**Comment by scoder** [comment]
You'd best implement this sort of thing in Cython instead of C. Speeds up the interface code, avoids reference leaks and makes supporting Py2/3 and things like file access or Unicode much easier.

**Comment by eriknyquist** [comment]
Cheers, I'll look into that
